package com.zaq.ssncv.ssncvapi.entity;

public class Interest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest.id
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest.image
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest.name
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest.description
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest.id
     *
     * @return the value of interest.id
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest.id
     *
     * @param id the value for interest.id
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest.image
     *
     * @return the value of interest.image
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest.image
     *
     * @param image the value for interest.image
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest.name
     *
     * @return the value of interest.name
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest.name
     *
     * @param name the value for interest.name
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest.description
     *
     * @return the value of interest.description
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest.description
     *
     * @param description the value for interest.description
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}