package com.zaq.ssncv.ssncvapi.entity;

import java.util.Date;

public class Spot {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.id
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.name
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.position
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.image
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.lastModified
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private Date lastmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spot.description
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.id
     *
     * @return the value of spot.id
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.id
     *
     * @param id the value for spot.id
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.name
     *
     * @return the value of spot.name
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.name
     *
     * @param name the value for spot.name
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.position
     *
     * @return the value of spot.position
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.position
     *
     * @param position the value for spot.position
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.image
     *
     * @return the value of spot.image
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.image
     *
     * @param image the value for spot.image
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.lastModified
     *
     * @return the value of spot.lastModified
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public Date getLastmodified() {
        return lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.lastModified
     *
     * @param lastmodified the value for spot.lastModified
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setLastmodified(Date lastmodified) {
        this.lastmodified = lastmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spot.description
     *
     * @return the value of spot.description
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spot.description
     *
     * @param description the value for spot.description
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}