package com.zaq.ssncv.ssncvapi.entity;

public class Surrounding {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surrounding.id
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surrounding.name
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surrounding.content
     *
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surrounding.id
     *
     * @return the value of surrounding.id
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surrounding.id
     *
     * @param id the value for surrounding.id
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surrounding.name
     *
     * @return the value of surrounding.name
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surrounding.name
     *
     * @param name the value for surrounding.name
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surrounding.content
     *
     * @return the value of surrounding.content
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surrounding.content
     *
     * @param content the value for surrounding.content
     * @mbg.generated Thu Oct 03 10:26:37 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}